apiVersion: apps/v1
kind: Deployment
metadata:
  name: soat-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: soat-api

  template:
    metadata:
      labels:
        app: soat-api

    spec:
      containers:
        - name: soat-api

          image: seuusuario/soat-api:latest

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: soat-api-config

            - secretRef:
                name: soat-api-secret

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"

            limits:
              memory: "512Mi"
              cpu: "500m"