apiVersion: v1
kind: Service

metadata:
  name: soat-api-service
  namespace: soat

spec:
  selector:
    app: soat-api

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

  type: LoadBalancer