apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: soat
type: Opaque
stringData:
  POSTGRES_DB:       soattechchallenge
  POSTGRES_USER:     postgres
  POSTGRES_PASSWORD: postgres